<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Gloify-Tech" failures="1" tests="6" name="Test" time="36.08" errors="0" timestamp="2023-03-30T19:13:17 IST">
  <testcase classname="com.inventsuite.testscript.logintestcase001" name="testcase" time="0.098"/>
  <testcase classname="com.inventsuite.testscript.logintestcase01" name="testlogin" time="0.014"/>
  <testcase classname="com.inventsuite.testscript.logintestcase02" name="testcase02" time="5.05"/>
  <testcase classname="com.inventsuite.testscript.logintestcase03" name="testcase03" time="0.073"/>
  <testcase classname="com.inventsuite.testscript.logintestcase04" name="testcase04" time="5.292"/>
  <testcase classname="com.inventsuite.testscript.logintestcase05" name="testcase05" time="12.247">
    <failure type="java.lang.AssertionError" message="expected [https://admin.gloify.co/dashboard1] but found [https://admin.gloify.co/dashboard]">
      <![CDATA[java.lang.AssertionError: expected [https://admin.gloify.co/dashboard1] but found [https://admin.gloify.co/dashboard]
at com.inventsuite.testscript.logintestcase05.testcase05(logintestcase05.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- testcase05 -->
</testsuite> <!-- Test -->
